In [2]:
from sklearn.preprocessing import PolynomialFeatures
import pandas as pd
import sklearn 
import matplotlib as mptl
import numpy as np


In [3]:
X = 2 * np.random.rand(100,1) # wektor pionowy
y = 4 + 3 * X + np.random.rand(100,1) #szum gaussa

In [8]:
X_b = np.c_[np.ones((100,1)), X]
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)
print(theta_best)

[[4.54069107]
 [2.92420422]]


In [15]:

X_new = np.array([[0], [2]])
X_new_b = np.c_[np.ones((2,1)), X_new]
y_predict = X_new_b.dot(theta_best)
y_predict

array([[ 4.54069107],
       [10.3890995 ]])

In [ ]:
from matplotlib import pyplot as plt
plt.plot(X, y, 'b.')

In [14]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X,y)
print(lin_reg.intercept_, lin_reg.coef_, "\n",lin_reg.predict(X_new))

[4.54069107] [[2.92420422]] 
 [[ 4.54069107]
 [10.3890995 ]]
