In [221]:
from sklearn import datasets
from sklearn.metrics import accuracy_score

In [222]:
data_breast_cancer_X, data_breast_cancer_y = datasets.load_breast_cancer(return_X_y= True, as_frame=True)
data_breast_cancer_y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: target, Length: 569, dtype: int64

In [223]:
data_breast_cancer_X = data_breast_cancer_X[(["mean area", "mean smoothness"])]
data_breast_cancer_X

mean area  mean smoothness
0       1001.0          0.11840
1       1326.0          0.08474
2       1203.0          0.10960
3        386.1          0.14250
4       1297.0          0.10030
..         ...              ...
564     1479.0          0.11100
565     1261.0          0.09780
566      858.1          0.08455
567     1265.0          0.11780
568      181.0          0.05263

[569 rows x 2 columns]

In [224]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_breast_cancer_X, data_breast_cancer_y, test_size=0.2)


In [225]:
import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
import pandas as pd

In [226]:
svm_clf = Pipeline([("linear_svc", LinearSVC(C=1,loss="hinge",random_state=42)),])

In [227]:
svm_clf.fit(X_train, y_train)

/opt/homebrew/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Pipeline(steps=[('linear_svc', LinearSVC(C=1, loss='hinge', random_state=42))])

In [228]:
acc = []
y_train_predict = svm_clf.predict(X_train)
y_test_predict = svm_clf.predict(X_test)
accuracy0 = np.array([accuracy_score(y_train, y_train_predict, normalize=True, sample_weight=None), accuracy_score(y_test, y_test_predict, normalize=True, sample_weight=None)])
accuracy0

array([0.63076923, 0.61403509])

In [229]:
svm_clf_scaled = Pipeline([("scaler", StandardScaler()),("linear_svc", LinearSVC(C=1,loss="hinge",random_state=42)),])
svm_clf_scaled.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('linear_svc', LinearSVC(C=1, loss='hinge', random_state=42))])

In [230]:
y_train_predict = svm_clf_scaled.predict(X_train)
y_test_predict = svm_clf_scaled.predict(X_test)
accuracy1 = np.array([accuracy_score(y_train, y_train_predict, normalize=True, sample_weight=None), accuracy_score(y_test, y_test_predict, normalize=True, sample_weight=None)])
accuracy1

array([0.89450549, 0.92982456])

In [231]:
acc = [accuracy0[0], accuracy1[0], accuracy0[1], accuracy1[1]]
acc 

[0.6307692307692307,
 0.8945054945054945,
 0.6140350877192983,
 0.9298245614035088]

In [232]:
import pickle
with open('bc_acc.pkl', 'wb') as f_cva:
    pickle.dump(acc, f_cva)

In [233]:
data_iris = datasets.load_iris()
data_iris_X, data_iris_y = datasets.load_iris(return_X_y=True, as_frame=True)
data_iris_X = data_iris_X[(["sepal length (cm)", "sepal width (cm)"])]
data_iris_y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [234]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_iris_X, data_iris_y, test_size=0.2)


In [235]:
svm_clf = Pipeline([("linear_svc", LinearSVC(C=1,loss="hinge",random_state=42)),])

In [236]:
svm_clf.fit(X_train, y_train)

/opt/homebrew/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Pipeline(steps=[('linear_svc', LinearSVC(C=1, loss='hinge', random_state=42))])

In [237]:
acc = []
y_train_predict = svm_clf.predict(X_train)
y_test_predict = svm_clf.predict(X_test)
accuracy0 = np.array([accuracy_score(y_train, y_train_predict, normalize=True, sample_weight=None), accuracy_score(y_test, y_test_predict, normalize=True, sample_weight=None)])
accuracy0

array([0.65833333, 0.73333333])

In [238]:
svm_clf_scaled = Pipeline([("scaler", StandardScaler()),("linear_svc", LinearSVC(C=1,loss="hinge",random_state=42)),])
svm_clf_scaled.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('linear_svc', LinearSVC(C=1, loss='hinge', random_state=42))])

In [239]:
y_train_predict = svm_clf_scaled.predict(X_train)
y_test_predict = svm_clf_scaled.predict(X_test)
accuracy1 = np.array([accuracy_score(y_train, y_train_predict, normalize=True, sample_weight=None), accuracy_score(y_test, y_test_predict, normalize=True, sample_weight=None)])
accuracy1

array([0.78333333, 0.86666667])

In [240]:
acc = [accuracy0[0], accuracy1[0], accuracy0[1], accuracy1[1]]
acc 

[0.6583333333333333,
 0.7833333333333333,
 0.7333333333333333,
 0.8666666666666667]

In [241]:
import pickle
with open('iris_acc.pkl', 'wb') as f_cva:
    pickle.dump(acc, f_cva)